# ==============================================================================
# SUPPORTED ANDROID EXECUTORS SPECIFICATION
# ==============================================================================
export EXECUTORS=(
    "Arceus X"
    "Delta"
    "Codex"
    "Fluxus"
    "Hydrogen"
    "VegaX"
)
