# ==============================================================================
# ROBLOX GAMES & UNIVERSE PLACE ID MAPPING
# ==============================================================================
export GAME_BLOX_FRUITS_NAME="Blox Fruits"
export GAME_BLOX_FRUITS_PID="2753915549"
export GAME_BLOX_FRUITS_SEA2="4442272183"
export GAME_BLOX_FRUITS_SEA3="7449423635"

export GAME_KING_LEGACY_NAME="King Legacy"
export GAME_KING_LEGACY_PID="4520749081"
export GAME_KING_LEGACY_SEA2="6367588219"
export GAME_KING_LEGACY_SEA3="15759515082"

export GAME_PET_SIM_99_NAME="Pet Simulator 99"
export GAME_PET_SIM_99_PID="8737877873"
export GAME_PET_SIM_99_TRADING="15502339080"

export GAME_FISCH_NAME="Fisch"
export GAME_FISCH_PID="16732694052"

export GAME_BLADE_BALL_NAME="Blade Ball"
export GAME_BLADE_BALL_PID="13772394625"

export GAME_DEEPWOKEN_NAME="Deepwoken"
export GAME_DEEPWOKEN_PID="4111023553"
