# ==============================================================================
# IPTABLES TPROXY STEALTH NETWORK CONFIGURATION
# ==============================================================================
export TPROXY_ROBLOX_PKG="com.roblox.client"
export TPROXY_TCP_PORT="10808"
export TPROXY_UDP_PORT="10808"
export TPROXY_DNS_PORT="53"
export TPROXY_DNS_REDIRECT="1.1.1.1:53"
export TPROXY_FAKE_IP_RANGE="198.18.0.0/15"
export TPROXY_MARK="1"
export TPROXY_TABLE="100"
