# ==============================================================================
# USER CUSTOM CONFIGURATION
# ==============================================================================
export USER_SELECTED_COUNTRY="MULTI"
export USER_SELECTED_GAME="Blox Fruits"
export USER_SELECTED_PLACE_ID="2753915549"
export USER_TPROXY_AUTOBOOT="false"
export USER_NOTIFICATIONS_ENABLED="true"
